# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-template
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::stringTie     
  - bioconda::cufflinks 
  - r-base=3.6.1
  - conda-forge::r-biocmanager
  - bioconda::bioconductor-ballgown
  - conda-forge::r-data.table=1.12.4
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-markdown=1.1

  ## bioconda packages, see above
